services:
  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    image: redis:7
    entrypoint:
      - redis-server
      - --appendonly
      - "no"
      - --requirepass
      - ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    env_file:
      - .env

  backend:
    build:
      context: node-backend
    ports:
      - "8000:8000"
    env_file:
      - node-backend/.env
    volumes:
      - ./node-backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: frontend
    volumes:
      - ./build:/app/dist

  celery:
    build:
      context: backend
    restart: always
    command: celery -A backend worker -l info --logfile /app/logs/celery.log
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: backend
    restart: always
    command: celery -A backend beat -l info --logfile /app/logs/celery.log
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    build:
      context: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/static:/var/www/static
      - ./backend/media:/var/www/media
      - ./build:/var/www/build
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/webroot:/var/www/certbot
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - backend

  certbot:
    image: certbot/certbot:v3.2.0
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/webroot:/var/www/certbot
    depends_on:
      - nginx
